### PR TITLE
Unpin rubin-sim in conda reqs

### PR DESCRIPTION
**Pull request by jmeyers314**

### CODE REVIEW

**Review by cwwalter — APPROVED** [review]
LGTM.. but do we want to pin it at 2.0.0 or leave it free?

**Comment by jchiang87** [comment]
I think we want to pin it at some version to avoid problems with the unit tests, especially the sky model tests.   That's why it was pinned at 1.1.1.

**Comment by rmjarvis** [comment]
If possible, we should try to leave it unpinned and only pin it again if there are problems.  People in the wild will continue to have whatever the latest is, so we will want to know when that is not compatible with how we are using it.

**Comment by jmeyers314** [comment]
I don't understand.  If I `conda install ...` packages one at a time, things work.  If I `conda install --file standalone_conda_requirements.txt"` the same packages, then conda stdouts that it's done, but returns a non-zero exit status anyway so GHA thinks error.  Gonna try with ` || true`...

**Comment by jmeyers314** [comment]
Seemed to get farther?  But similar error when installing the test requirements?  adding more `|| true`...

**Comment by jmeyers314** [comment]
Okay, that seems to have worked (rebasing now to clean up the history).  Note I fixed a deprecation warning too in case anyone wants to review that.

**Review by rmjarvis — APPROVED** [review]

**Comment by cwwalter** [comment]
The pickle to fits change of the fringing file is for the deprecation warning?

**Comment by jmeyers314** [comment]
> The pickle to fits change of the fringing file is for the deprecation warning?

Exactly.  The pickle was holding a deprecated interpolation object, so I extracted the values-to-be-interpolated and put them in a fits instead.

**Pull request merged**
