### PR TITLE
Temporary fix for downloading rubin_sims data files while USDF is down.

### PR DESCRIPTION
**Pull request by cwwalter**
Get the files from Duke this week.

### CODE REVIEW

**Comment by cwwalter** [comment]
The downloads are working.  But the CI tests are failing for some reason on skyCatalog tests with errors 

```ModuleNotFoundError: No module named 'git' ```

**Comment by jmeyers314** [comment]
Looks like SkyCatalogs needs to add https://pypi.org/project/GitPython/ to its dependencies.  You could probably just add that straight to .github/workflows/ci.yml for now if you like.

**Comment by cwwalter** [comment]
OK finally all passes.  @jchiang87 please review and I will merge.

**Review by jchiang87 — APPROVED** [review]
Thanks, lgtm.

**Pull request merged**
