### PR TITLE
initialize _column_cache in imSim__init__

### PR DESCRIPTION
**Pull request by danielsf**

### CODE REVIEW

**Comment by jchiang87** [comment]
Regarding the missing `_column_cache` attribute:  The problem is that the superclass' `__init__` can't be called in the default case because we don't have a `CatalogDBObject` to pass it (i.e., see the if block at the top of `imSim__init__`: https://github.com/LSSTDESC/imSim/blob/master/python/desc/imsim/imSim_class_factory.py#L44) so those attributes were never set.   Ideally, we should call the superclass constructor so that any other attributes that get used down the road will be available.  This goes back, of course, to discussions at #25 and #30.

**Comment by cwwalter** [comment]
> Ideally, we should call the superclass constructor so that any other attributes that get used down the road will be available

I remember that one of the changes in Python 3 had to do with how Super was implemented/used.  Would it be different there?

**Comment by cwwalter** [comment]
Just curious BTW, as you say the real solution is related to discussions in #25 etc.

**Comment by jchiang87** [comment]
I'm not sure...the differences in super for python3 look largely syntactic...I don't think it would fundamentally change the issue regarding passing a CatalogDBObject.

**Pull request merged**
