### PR TITLE
Add _wavefront to OptWF, since needed with GalSim 2.0

### PR DESCRIPTION
**Pull request by rmjarvis**
@villarrealas has been testing using ImSim with GalSim 2.0 and ran into a bug that the OptWF screen needs to have _wavefront (in addition to _wavefront_gradient which was already there).

I think I added this properly, but @jmeyers314 should check this out to make sure I didn't miss something, since he is the original author of this code.

### CODE REVIEW

**Comment by rmjarvis** [comment]
I just know that Antonio reported that a test imsim run crashed with
```
AttributeError: 'OptWF' object has no attribute '_wavefront'
```
Antonio, maybe you can give the full traceback.  It's possible we doing something wrong currently if Josh doesn't think we should have needed this.

**Comment by villarrealas** [comment]
`multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/lsst/software/stack/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/DC2/imSim/python/desc/imsim/ImageSimulator.py", line 362, in __call__
    gs_interpreter.drawObject(gs_obj)
  File "/DC2/sims_GalSimInterface/python/lsst/sims/GalSimInterface/galSimInterpreter.py", line 764, in drawObject
    centeredObj = self.findAllDetectors(gsObject)
  File "/DC2/sims_GalSimInterface/python/lsst/sims/GalSimInterface/galSimInterpreter.py", line 191, in findAllDetectors
    centeredObj = self.createCenteredObject(gsObject)
  File "/DC2/sims_GalSimInterface/python/lsst/sims/GalSimInterface/galSimInterpreter.py", line 468, in createCenteredObject
    centeredObj = self.drawSersic(gsObject, psf=psf)
  File "/DC2/sims_GalSimInterface/python/lsst/sims/GalSimInterface/galSimInterpreter.py", line 383, in drawSersic
    obj=centeredObj)
  File "/DC2/sims_GalSimInterface/python/lsst/sims/GalSimInterface/galSimPSF.py", line 73, in applyPSF
    obj = galsim.Convolve(obj, psf)
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/galsim/2.0.7.lsst2/lib/python/galsim/convolve.py", line 64, in Convolve
    return Convolution(*args, **kwargs)
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/galsim/2.0.7.lsst2/lib/python/galsim/convolve.py", line 214, in __init__
    self._obj_list = [obj.withGSParams(self._gsparams) for obj in args]
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/galsim/2.0.7.lsst2/lib/python/galsim/convolve.py", line 214, in <listcomp>
    self._obj_list = [obj.withGSParams(self._gsparams) for obj in args]
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/galsim/2.0.7.lsst2/lib/python/galsim/utilities.py", line 1427, in f
    return self.mthd(obj, *args, **kwargs)
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/galsim/2.0.7.lsst2/lib/python/galsim/phase_psf.py", line 1328, in withGSParams
    ret = copy(self)
  File "/opt/lsst/software/stack/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/copy.py", line 96, in copy
    rv = reductor(4)
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/galsim/2.0.7.lsst2/lib/python/galsim/phase_psf.py", line 1399, in __getstate__
    self._prepareDraw()
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/galsim/2.0.7.lsst2/lib/python/galsim/phase_psf.py", line 1367, in _prepareDraw
    self._screen_list._prepareDraw()
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/galsim/2.0.7.lsst2/lib/python/galsim/phase_psf.py", line 856, in _prepareDraw

    wf = self._screen_list._wavefront(u, v, None, self.theta)
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/galsim/2.0.7.lsst2/lib/python/galsim/phase_psf.py", line 915, in _wavefront
    return np.sum([layer._wavefront(u, v, t, theta) for layer in self], axis=0)
  File "/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/galsim/2.0.7.lsst2/lib/python/galsim/phase_psf.py", line 915, in <listcomp>
    return np.sum([layer._wavefront(u, v, t, theta) for layer in self], axis=0)
AttributeError: 'OptWF' object has no attribute '_wavefront'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/DC2/ALCF_1.2i/scripts/run_imsim.py", line 128, in <module>
    log_level=args.log_level)
  File "/DC2/ALCF_1.2i/scripts/run_imsim.py", line 80, in run_imsim
    image_simulator.run(processes=processes, node_id=node_id)
  File "/DC2/imSim/python/desc/imsim/ImageSimulator.py", line 295, in run
    return [res.get() for res in results]
  File "/DC2/imSim/python/desc/imsim/ImageSimulator.py", line 295, in <listcomp>
    return [res.get() for res in results]
  File "/opt/lsst/software/stack/python/miniconda3-4.5.4/envs/lsst-scipipe-fcd27eb/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
AttributeError: 'OptWF' object has no attribute '_wavefront'
`

**Comment by villarrealas** [comment]
```/DC2/sims_photUtils/python/lsst/sims/photUtils/Sed.py:916: DeprecationWarning: Sed.setupCCMab is now deprecated in favor of Sed.setupCCM_ab
  DeprecationWarning)
/DC2/sims_photUtils/python/lsst/sims/photUtils/Sed.py:1048: DeprecationWarning: Sed.addCCMDust is now deprecated in favor of Sed.addDust
  DeprecationWarning)
/opt/lsst/software/stack/stack/miniconda3-4.5.4-fcd27eb/Linux64/galsim/2.0.7.lsst2/lib/python/galsim/errors.py:424: GalSimWarning: AtmosphericScreen was instantiated for photon shooting. Drawing now with FFT may yield surprising results.
  warnings.warn(message, GalSimWarning)```

I thought these warnings would not be relevant, but it sounds like they might be?

**Comment by jmeyers314** [comment]
>it sounds like they might be?

Yep.  I think that supports my hypothesis.

Looking at adding a failing unit test to GalSim now to see if I can reproduce...

**Comment by rmjarvis** [comment]
Interesting.  So we should probably fix this about `PhaseScreenPSF.withGSParams` before switching over to imsim using GalSim 2.0, I guess.  

I'll have to think a bit more probably about where to put the fix.  I remember it being a little tricky getting the withGSParams stuff working in these because of the ambiguity about which kind of object they would eventually be, so they weren't really immutable.  For instance I think I wanted to make sure that for a psf with an unprepared screen, the following would work:
```
psf2 = psf.withGSParams(gsp)
psf.drawImage(...)
psf2.drawImage(method='phot', ...)
```
But that might be asking too much.  We could instead have withGSParams point to the same (unprepared) back-end screens and just point out that if `psf` in this example is used one way, then `psf2` also needs to be drawn the same way.  The user can always manually copy if they don't want that.

**Comment by jmeyers314** [comment]
Here's a pretty succinct failing test:

```python
def test_withGSP():
    class DummyScreen(galsim.OpticalScreen):
        def _wavefront(self, *args):
            raise RuntimeError("Shouldn't reach this")

    screen = DummyScreen(1.0)
    psl = galsim.PhaseScreenList(screen)
    psf = psl.makePSF(exptime=0.02, time_step=0.01, diam=1.1, lam=1000.0)
    psf2 = psf.withGSParams(galsim.GSParams(folding_threshold=6e-3))
```

**Comment by cwwalter** [comment]
Hmm... I'm a bit confused... Jim tested GalSim 2.0 before. Is this something that only happens sporadically or is it somehow related to other recent changes?

**Comment by rmjarvis** [comment]
It only happens for the bright stars where we need to give them a nonstandard gsparams to increase their relative precision.  So not super rare, but maybe not in the test Jim did.

**Comment by jmeyers314** [comment]
Okay, there's a PR for this now in GalSim (https://github.com/GalSim-developers/GalSim/pull/991).  @villarrealas , is it possible for you to rerun your imSim tests using this GalSim branch?

**Comment by villarrealas** [comment]
I can give it a shot. It might take a little bit of time for me to work out how the Singularity image needs to change, but that isn't the end of the world.

**Comment by rmjarvis** [comment]
To be clear (just in case it wasn't), Josh and I think the correct fix for this problem is actually what is in the [GalSim PR](GalSim-developers/GalSim#991).  The code here is probably not actually helpful.  So once that PR is verified to work correctly, this PR should be closed without merging.

**Comment by cwwalter** [comment]
Got it. Thanks.

**Comment by jchiang87** [comment]
I'm closing this since the galsim PR that Mike mentions above was merged.

**Comment by jchiang87** [comment]
I'm re-opening this, though a new issue may actually be called for.  Running the `fft_switch` branches of `imSim` and `sims_GalSimInterface` and galsim v2.1, I'm getting
```
/home/galsim_local/python/galsim/errors.py:429: GalSimWarning: AtmosphericScreen was instantiated for photon shooting. Drawing now with FFT may yield surprising results.
  warnings.warn(message, GalSimWarning)
Traceback (most recent call last):
  File "/home/imSim/bin/imsim.py", line 91, in <module>
    image_simulator.run(processes=args.processes)
  File "/home/imSim/python/desc/imsim/ImageSimulator.py", line 250, in run
    results.append(simulate_sensor(self.gs_obj_dict[det_name]))
  File "/home/imSim/python/desc/imsim/ImageSimulator.py", line 370, in __call__
    fft_sb_thresh=fft_sb_thresh)
  File "/home/sims_GalSimInterface/python/lsst/sims/GalSimInterface/galSimInterpreter.py", line 902, in drawObject
    gain=detector.photParams.gain)
  File "/home/galsim_local/python/galsim/gsobject.py", line 1585, in drawImage
    self._prepareDraw()
  File "/home/galsim_local/python/galsim/transform.py", line 274, in _prepareDraw
    self._original._prepareDraw()
  File "/home/galsim_local/python/galsim/convolve.py", line 285, in _prepareDraw
    obj._prepareDraw()
  File "/home/galsim_local/python/galsim/phase_psf.py", line 1397, in _prepareDraw
    self._screen_list._prepareDraw()
  File "/home/galsim_local/python/galsim/phase_psf.py", line 868, in _prepareDraw
    psf._step()
  File "/home/galsim_local/python/galsim/phase_psf.py", line 1406, in _step
    wf = self._screen_list._wavefront(u, v, None, self.theta)
  File "/home/galsim_local/python/galsim/phase_psf.py", line 927, in _wavefront
    return np.sum([layer._wavefront(u, v, t, theta) for layer in self], axis=0)
  File "/home/galsim_local/python/galsim/phase_psf.py", line 927, in <listcomp>
    return np.sum([layer._wavefront(u, v, t, theta) for layer in self], axis=0)
AttributeError: 'OptWF' object has no attribute '_wavefront'
```
I verified that Josh's `test_withGSP` function works fine with the same set up, so there's still a lingering problem here.

**Pull request closed without merging**
