### PR TITLE
U/jchiang/simple faint interface

### PR DESCRIPTION
**Pull request by jchiang87**

### CODE REVIEW

**Comment by cwwalter** [comment]
I'm soft of  confused bywhat is going one with this one... 

Isn't turning on the interface in #181?  This seems to have a bunch of stuff in the other PRs that (haven't?) been already merged?

**Comment by cwwalter** [comment]
OK but I'm just sort of confused... is there anything in here which is not in the other PRs like
#174, #176, #181 etc (that were merged to the branch)?  

Can't you go back and merge those branches individually to master? Or is there some change in this one that isn't in the others (that's the part I am confused by...)?

**Comment by cwwalter** [comment]
Oops forgot to type: Also wondering if this one has the commits we wanted to leave out in it?

**Comment by jchiang87** [comment]
I'll merge this at 9am tomorrow PT unless I hear otherwise.

**Pull request merged**
