### PR TITLE
add checkpointing options

### PR DESCRIPTION
**Pull request by jchiang87**

### CODE REVIEW

**Comment by jchiang87** [comment]
Unless there are objections, I'll merge this branch into master at 12pm PT tomorrow.  The related changes in `sims_GalSimInterface` have been [merged into master](https://github.com/lsst/sims_GalSimInterface/pull/42).

**Comment by cwwalter** [comment]
Ok, thanks that sounds good.  Btw are the Travis builds supposed to be working now or no?

**Comment by jchiang87** [comment]
It's choking on this branch because the corresponding sims_GalSimInterface changes aren't in the docker image it's using.  So, unless we have travis checkout a local copy, it will be broken until we get a new image.

**Comment by cwwalter** [comment]
Ah. OK got it.

**Comment by danielsf** [comment]
Looks good to me

**Pull request merged**
