### PR TITLE
Update docker image

### PR DESCRIPTION
**Pull request by stuartmcalpine**
1) Updated the imsim-env docker image (update dependencies)

2) Updated the install docs to include information about the imsim-env docker image

3) Added a ci workflow that tests imSim within the docker image

### CODE REVIEW

**Review by cwwalter — APPROVED** [review]
I'm not really a docker user. But the parts of this I understand look OK to me.

I think my only comment would be that for normal users, I'm not sure recommending  docker as the preferred installation method in the text here:

> for that reason we recommend working within the *imSim* *Docker* image, where
 the LSST software stack is pre-installed. Alternatively, you can use the
 *imSim* *Docker* file as a template to build your own *Docker* image, or,
 another option is to work within a *Conda* environment that gets the LSST stack
 through *Stackvana*. The three installation options are detailed below.

is really the best advice.  For most people, using stackvana (or maybe cmvfms if they have it) is going to be easier.

**Comment by stuartmcalpine** [comment]
Thanks Chris,

I didn't realise it was that was round. I've reworded the docs to favour Conda (or at least mentioned that first)

**Comment by stuartmcalpine** [comment]
@jchiang87 good to merge this?

**Comment by jchiang87** [comment]
> @jchiang87 good to merge this?

It's been approved, so I would think yes.

**Pull request merged**
