### PR TITLE
use lowercased token so that 'sersic2D' yields the right starting index for the dust entries

### PR DESCRIPTION
**Pull request by jchiang87**

### CODE REVIEW

**Comment by cwwalter** [comment]
Because GalSim uses sersic2d ?

**Comment by jchiang87** [comment]
The skyCatalog instcat entries and existing phosim instcats use 'sersic2D', so this is to avoid a problem given how the dict is defined [here](https://github.com/LSSTDESC/imSim/blob/5f5290abac48d8e333941d586605b0e8d6bb7f92/imsim/instcat.py#L116).  This change is also consistent with usage [elsewhere](https://github.com/LSSTDESC/imSim/blob/5f5290abac48d8e333941d586605b0e8d6bb7f92/imsim/instcat.py#L211).

**Comment by cwwalter** [comment]
OK. Got it. Change LGTM.

**Review by rmjarvis — APPROVED** [review]
Good.  That was my oversight.  Thanks for fixing.

**Pull request merged**
