### PR TITLE
set allowed_chips

### PR DESCRIPTION
**Pull request by jchiang87**
I've been using this for the DC1 production runs and it's been working fine.

### CODE REVIEW

**Comment by cwwalter** [comment]
This looks fine.. but this just sets the list of chips.  Did we previously check in something that uses it?

**Comment by jchiang87** [comment]
I'm not sure I understand your question.  Every time you run imsim.py with a single sensor selected, it will be used.  If this code isn't present, occasionally FITS images for chips that were not requested will be generated because of a bright source near its edge.

**Comment by cwwalter** [comment]
I just mean all the PR does is add:

> phoSimStarCatalog.allowed_chips = [arguments.sensor]

I can't remember where the code that uses this variable is.  I'm just checking you are not forgetting to check something in.

**Comment by jchiang87** [comment]
The code that uses that is in the sims_GalSimInterface code.

**Comment by cwwalter** [comment]
Ah, OK got it.

**Pull request merged**
