### PR TITLE
fft diffraction: Fix spike offset

### PR DESCRIPTION
**Pull request by g-braeunlich**

### CODE REVIEW

**Comment by g-braeunlich** [comment]
The bug was in principle, that I used `mode="same"` instead of `mode="full"`.
I moved the convolution logic into its own function and added a test which checks convolution + adding images

**Review by jchiang87 — APPROVED** [review]
Thanks! lgtm

**Review by rmjarvis — APPROVED** [review]
Seems right.  Do you have an update to how things look in practice.  E.g. this kind of thing that precipitated the issue?
image

**Comment by jchiang87** [comment]
I've made the comparison for the test inputs I posted in our [slack thread](https://lsstc.slack.com/archives/CHXKSF3HC/p1691542283369069?thread_ts=1691420959.989129&cid=CHXKSF3HC).  Left is before the fix and right is with these changes.
PR402_fix

**Comment by rmjarvis** [comment]
Great!  Lgtm.

**Comment by cwwalter** [comment]
Great!

**Pull request merged**
